##' Running examples 
##'
##' This includes the \donttest{} sections of the examples.
##' @title Running examples
##' @param pkgName Name of package
##' @param Source directory in which the package source code lives
##' @param valgrind does not work yet
##' @param verbose jabber or not
##' @return nothing
##' @author Thomas A. Gerds
##' @examples
##' 
##' run(prodlim)
##'
##' @export
run <- function(pkgName,
                Source=options()$refreshSource,
                valgrind = FALSE,
                verbose=1){
    pkgName <- as.character(substitute(pkgName))
    pos <- match(paste("package:",pkgName,sep=""),search(),nomatch=0)
    if (pos==0) stop("Package not in search() path.")
    funs <- ls(pos)
    do.call("require",list(pkgName))
    pdf.name <- paste("/tmp/",pkgName,"-examples.pdf",sep="")
    pdf(pdf.name)
    par(ask=FALSE)
    plot(0,0,type="n",axes=FALSE,xlab="",ylab="")
    text(0,0,paste("Collection of plots\ngenerated by the example\nsections of package:\n",pkgName,sep=""),cex=2)
    for (f in funs){
        print(f)
        plot(0,0,type="n",axes=FALSE,xlab="",ylab="")
        text(0,0,paste("Collection of plots\ngenerated by the example\nsections of function:\n",f,sep=""),cex=2)        
        try(do.call(example,list(f,ask=0L,run.dontrun=1L,run.donttest=0L)),silent=TRUE)
    }
    dev.off()
    if (file.exists(pdf.name))
        system(paste("evince",pdf.name,"&"))
}
    
